/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_tomydear_NetCore */

#ifndef _Included_com_example_tomydear_NetCore
#define _Included_com_example_tomydear_NetCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_tomydear_NetCore
 * Method:    Init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_tomydear_NetCore_Init
  (JNIEnv *, jobject);

/*
 * Class:     com_example_tomydear_NetCore
 * Method:    Connect
 * Signature: (Ljava/lang/String;C)I
 */
JNIEXPORT jint JNICALL Java_com_example_tomydear_NetCore_Connect
  (JNIEnv *, jobject, jstring, jchar);

/*
 * Class:     com_example_tomydear_NetCore
 * Method:    Stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_tomydear_NetCore_Stop
  (JNIEnv *, jobject);

/*
 * Class:     com_example_tomydear_NetCore
 * Method:    Send
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_tomydear_NetCore_Send
  (JNIEnv *, jobject);

/*
 * Class:     com_example_tomydear_NetCore
 * Method:    Recv
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_tomydear_NetCore_Recv
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
